name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build-ios:
    name: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install quilt
        run: brew install quilt

      - name: Install deps
        run: bun install

      - name: Build
        run: bun run build
