name: PR Code Checks
on: [pull_request]

jobs:
  main:
    runs-on: macos-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        name: checkout code
      - uses: oven-sh/setup-bun@v2
        name: setup bun
      - name: install quilt
        run: brew install quilt
      - uses: nttld/setup-ndk@v1.6.0
        id: setup-ndk
        with:
          ndk-version: r29
          add-to-path: false
      - name: install deps
        run: bun install
      - name: check bun lockfile
        run: git diff --exit-code HEAD -- bun.lock || exit 1
      - name: build
        run: ANDROID_NDK_HOME="${{ steps.setup-ndk.outputs.ndk-path }}" bun run build
