name: PR Code Checks
on: [pull_request]

jobs:
  main:
    runs-on: macos-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        name: checkout code
      - uses: oven-sh/setup-bun@v2
        name: setup bun
      - name: install quilt
        run: brew install quilt@0.69
      - name: install android ndk
        run: brew install android-ndk@29
      - name: install deps
        run: bun install
      - name: check bun lockfile
        run: git diff --exit-code HEAD -- bun.lock || exit 1
      - name: build
        run: ANDROID_NDK_HOME="$HOMEBREW_PREFIX/share/android-ndk" bun run build
